services:
  postgres:
    image: postgres:16.2
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5433:5432"
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
    driver: local