spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    password: root
    username: root
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
      orm:
        jdbc:
          bind: TRACE
    type:
      descriptor:
        sql:
          BasicBinder: TRACE