spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres?currentSchema=public
    password: root
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        physical_naming_strategy: com.phuocvh.common.config.CustomPhysicalNamingStrategy
        globally_quoted_identifiers: true
    show-sql: true
  devtools:
    restart:
      enabled: false
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
      orm:
        jdbc:
          bind: TRACE
    type:
      descriptor:
        sql:
          BasicBinder: TRACE